# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Restricted Mean Survival Time
#'
#' @param status Status, coded as 0 for censoring, 1 for death.
#' @param time Observation time.
#' @param extend Extend AUC calculation if tau exceeds max(time)?
#' @param tau Truncation time.
#' @return Numeric restricted mean survival time.
#' @export
RMST <- function(status, time, extend = FALSE, tau = NULL) {
    .Call(`_MRMST_RMST`, status, time, extend, tau)
}

#' RMST Influence Function
#'
#' Influence function of the restricted mean survival time at time t.
#'
#' @param status Status, coded as 0 for censoring, 1 for death.
#' @param time Observation time.
#' @param trunc_time Truncation time.
#' @return Numeric vector of influence function values for each observation.
CalcPsiRMST <- function(status, time, trunc_time) {
    .Call(`_MRMST_CalcPsiRMST`, status, time, trunc_time)
}

#' Generate Perturbations
#'
#' @param psi Per-subject influence values.
#' @param n_boot Number of perturbations.
#' @return Numeric vector.
#' @section Notes:
#' The random seed should be set in R prior to calling this function.
GenPerturb <- function(psi, n_boot) {
    .Call(`_MRMST_GenPerturb`, psi, n_boot)
}

