# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Restricted Mean Survival Time
#'
#' @param status Status, coded as 0 for censoring, 1 for death.
#' @param time Observation time.
#' @param extend Extend AUC calculation if tau exceeds max(time)?
#' @param tau Truncation time.
#' @return Numeric restricted mean survival time.
#' @export
RMST <- function(status, time, extend = FALSE, tau = NULL) {
    .Call(`_MRMST_RMST`, status, time, extend, tau)
}

#' Integrate Kaplan Meier
#'
#' Integrate the Kaplan-Meier curve between two values.
#' 
#' @param status Status, coded as 0 for censoring, 1 for death.
#' @param time Observation time.
#' @param tau Truncation time.
CalcPsiRMST <- function(status, time, tau) {
    .Call(`_MRMST_CalcPsiRMST`, status, time, tau)
}

#' Generate Perturbations
#'  
#' Generates realizations of \eqn{\frac{1}{n}\sum_{i=1}^{n}\psi_{i}w_{i}},
#' where \eqn{\psi_{i}} is the influence function for the ith subject and the
#' \eqn{w_{i}} are IID random weights.
#' 
#' @section Notes:
#' The random seed should be set in R prior to calling this function.
#'
#' @param psi Per-subject influence values.
#' @param n_boot Number of perturbations.
#' @return Numeric vector.
GenPerturb <- function(psi, n_boot) {
    .Call(`_MRMST_GenPerturb`, psi, n_boot)
}

